version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "static-content-site"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-<RandomID>>"
s3_prefix = "static-content-site"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
